version: 2

sources:
  - name: MYSQL_RDS_SAKILA
    database: SAKILA_RAW
    tables:
      - name: ACTOR
      - name: ADDRESS
      - name: STORE
      - name: STAFF
      - name: CUSTOMER
      - name: CITY
      - name: COUNTRY
      - name: RENTAL
      - name: FILM
  - name: PUBLIC
    database: SAKILA_DW
    tables:
      - name: DIM_DATE
      - name: DIM_TIMEOFDAY